### ISSUE TITLE
weights link

### ISSUE THREAD

**Issue by kaanulgen** [gunaytemur/With-Yolov3-Buy-Sell-on-Candlestick#1]
Merhaba Günay Hocam,

Tez çalışmanız sonucunda elde ettiğiniz model ağırlıklarını tekrardan paylaşma imkanınız var mı? Maalesef paylaştığınız link üzerinden ilgili değerlere ulaşılamıyor.

İyi çalışmalar diliyorum,
E. Kaan Ülgen

**Comment by gunaytemur** [comment]
linkin süresi dolmuş, yeniledim. iyi çalışmalar dilerim.

**Comment by kaanulgen** [comment]
Teşekkür ederim hocam. İyi çalışmalar diliyorum
